### ISSUE TITLE
Image attribute on node seems to be unsupported

### ISSUE THREAD

**Issue by Johanneslueke** [Robotechnic/diagraph#11]
Hello, 

I am currently trying to draw a network diagram with the help of your extension. unfortunately it seems i cannot load images onto nodes to change their appearance. But perhaps i am doing something wrong. 

the *.typ and image file are within the same folder. according to GraphViz documentation that is basically the only way its supported:
more local than " **./**\ cloud.png" is not possible in my eyes.
![image](https://github.com/Robotechnic/diagraph/assets/3592317/b4468d2d-ced7-4c8f-8781-24c03f6d61bf)

My expectation would have been that the node loads the cloud.png file. but this does not happen.

The diagram is as follow:

```
    #raw-render(
      ```dot
      digraph {
       rankdir=LR
        node[image="./cloud.png" shape=none]
        a -> b
      }
      ```
    )
```

which results in this: 
![image](https://github.com/Robotechnic/diagraph/assets/3592317/69ab7d04-373e-4507-8775-051a51da9ee0)


Are images even supported by your extension?

**Comment by Robotechnic** [comment]
Hello,

Graphviz doesn't have access to the file system. So, it can't display images like that. However, you can do that:

```typst
#raw-render(```
	digraph {
		"Hello" -> "World"
		a -> "Hello"
	}
```, labels: (
	a: image("Cloud.jpg", width: 5em)
))
```
It will display the graph like this:
![image](https://github.com/Robotechnic/diagraph/assets/45141234/a172525e-ab75-44ea-80f9-c81964b6c026)

In future versions, we will add support for images because it's a thing we didn't think about, but now, it is the only way.

**Comment by Johanneslueke** [comment]
thank you for the quick response. that workaround must suffice for now :smile: . eagerly awaiting this new feature.
